-- MENAMPILKAN SEMUA DATA DOSEN
SELECT * FROM Dosen;

-- TAMPILKAN DATA TABEL DOSEN DENGAN HNAYA MENAMPILKAN KOLOM NamaDosen
SELECT NamaDosen FROM Dosen;

-- TAMPILKAN NAMA DOSEN SAJA DENGAN PRODI INFORMATIKA
SELECT NamaDosen, Prodi FROM Dosen WHERE Prodi = 'Informatika';

-- TAMPILKAN NAMA DOSEN YANG MENGAJAR BASIS DATA
SELECT D.NamaDosen, MK.NamaMK
FROM Dosen as D
INNER JOIN MataKuliah as MK ON D.DosenID = MK.DosenID 
WHERE MK.NamaMK = 'Basis Data';

-- TAMPILKAN NAMA DOSEN YANG MENGAJAR BASIS DATA (S QUERY)
SELECT NamaDosen
FROM Dosen 
WHERE DosenID = (
    SELECT DosenID
    FROM MataKuliah
    WHERE NamaMK = 'Basis Data'
);

-- TAMPILKAN MATA KULIAH YANG DIAJAR OLEH Agus Hidayat, M.Kom
-- S QUERY
SELECT NamaMK
FROM MataKuliah
WHERE DosenID = (
    SELECT DosenID
    FROM Dosen
    WHERE NamaDosen = 'Agus Hidayat, M.Kom'
);

-- MENAMPILKAN MAHASISWA YANG MEMILIKI NILAI 'A'
SELECT NamaMahasiswa
FROM Mahasiswa
WHERE MahasiswaID IN (
    SELECT MahasiswaID
    FROM Nilai
    WHERE NilaiAkhir = 'A'
);

-- TAMMPILKAN MATAKUIAH DENGAN NILAI AKHIR 'A'
SELECT NamaMK
FROM MataKuliah
WHERE MataKuliahID IN (
    SELECT MataKuliahID
    FROM Nilai
    WHERE NilaiAkhir = 'A'
);

-- MENAMPILKAN DAFTAR PRODI YANG MAHASISWA NYA > 2
SELECT Prodi, TotalMhs
FROM (
    SELECT Prodi, COUNT(*) as TotalMhs
    FROM Mahasiswa
    GROUP BY Prodi
) AS HitungMhs 
WHERE TotalMhs > 2;

WITH MhsIF AS (
    SELECT *
    FROM Mahasiswa
    WHERE Prodi = 'Informatika'
)
SELECT * FROM MhsIF;

-- BUAT TABLE SEMENTARA UNTUK MENGHITUNG
-- JUMLAH MAHASISWA PER PRODI
WITH MahasiswaPerProdi AS (
    SELECT Prodi, COUNT(*) AS Total
    FROM Mahasiswa
    GROUP BY Prodi
)
SELECT * FROM MahasiswaPerProdi WHERE Total > 2;

-- SET OPERATORS
-- UNION MENGGABUNGKAN DAFTAR NAMA DOSEN DAN DAFTAR NAMA MAHASISWA
SELECT NamaDosen FROM Dosen
UNION
SELECT NamaMahasiswa FROM Mahasiswa

-- UNINON : MENGGABUNGKAN RUANGAN YANG KAPASITAS NYA > 40 DAN YANG
-- KAPASISTASNYA < 40
SELECT Kapasitas FROM RUANGAN WHERE Kapasitas > 40
UNION
SELECT Kapasitas FROM RUANGAN WHERE Kapasitas < 40

-- INTERSECT
-- MENGGABUNGKAN MAHASISWA ID YANG ADA DI TABEL KRS DAN TABEL NILAI
SELECT MahasiswaID FROM KRS
INTERSECT
SELECT MahasiswaID FROM Nilai

-- GABUNGKAN MATAKULIAH ID YANG ADA DI TABEL MATAKULIAH DAN TABEL NILAI
SELECT MataKuliahID FROM MataKuliah
INTERSECT
SELECT MataKuliahID FROM Nilai;